### ISSUE TITLE
CRASH when app go in background

### ISSUE THREAD

**Issue by doffi88** [googlesamples/android-FingerprintDialog#42]
hy  guys, sorry for my english , I have this problem when I close authentication dialog and app go in background

D/AbstractTracker: Event success
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.IllegalStateException: Binder has been finalized!
              at android.os.BinderProxy.transactNative(Native Method)
              at android.os.BinderProxy.transact(Binder.java:536)
              at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1302)
              at android.security.KeyStore.abort(KeyStore.java:496)
              at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:680)
              at android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(AndroidKeyStoreUnauthenticatedAESCipherSpi.java:73)
              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:219)
              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:197)
              at java.lang.Thread.run(Thread.java:818)

how can I resolve this issue?

thanks in advance

**Comment by axnd** [comment]
I'm running into the same issue, only difference is I'm using RSA:

```
java.lang.IllegalStateException: Binder has been finalized!
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:503)
    at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1302)
    at android.security.KeyStore.abort(KeyStore.java:496)
    at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:680)
    at android.security.keystore.AndroidKeyStoreRSACipherSpi$PKCS1Padding.finalize(AndroidKeyStoreRSACipherSpi.java)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
    at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by IgorGanapolsky** [comment]
I am getting the same error.  Is there a solution for this?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
