### ISSUE TITLE
Exception thrown after fingerprint app is closed ,as mentioned below

### ISSUE THREAD

**Issue by sairajkishore** [googlesamples/android-FingerprintDialog#50]
java.lang.IllegalStateException: Binder has been finalized!
                                                                                   at android.os.BinderProxy.transactNative(Native Method)
                                                                                   at android.os.BinderProxy.transact(Binder.java:628)
                                                                                   at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1387)
                                                                                   at android.security.KeyStore.abort(KeyStore.java:879)
                                                                                   at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:744)
                                                                                   at android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(AndroidKeyStoreUnauthenticatedAESCipherSpi.java)
                                                                                   at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                                                   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                                                   at java.lang.Thread.run(Thread.java:762)

**Comment by KalpeshJadvani** [comment]
also i got this error but i can't find 

why this happened

**Comment by srikanthnama** [comment]
I also got the same issue

**Comment by hirenshah** [comment]
Anyone?

**Comment by jimmysuncpt** [comment]
me too

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
