### ISSUE TITLE
Meizu crashed when using AndroidKeyStore

### ISSUE THREAD

**Issue by jimmysuncpt** [googlesamples/android-FingerprintDialog#54]
There are crashes in some Meizu phones, such as M5 note, PRO 7 Plus and so on. The system version is Android 7.0. The log is:
```
java.util.concurrent.TimeoutException: android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(AndroidKeyStoreUnauthenticatedAESCipherSpi.java) timed out after 20 seconds
	at android.os.BinderProxy.transactNative(BinderProxy.java)
	at android.os.BinderProxy.transact(BinderProxy.java:626)
	at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1341)
	at android.security.KeyStore.abort(KeyStore.java:538)
	at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:744)
	at android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi$CBC$PKCS7Padding.finalize(AndroidKeyStoreUnauthenticatedAESCipherSpi.java)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:239)
	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:226)
	at java.lang.Thread.run(Thread.java:761)
```
How to fix it?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
